CREATE ROLE zushi WITH LOGIN NOSUPERUSER NOCREATEROLE NOREPLICATION CONNECTION LIMIT 5 PASSWORD 'zushi';
CREATE DATABASE zushi OWNER zushi;


GRANT ALL PRIVILEGES ON DATABASE zushi TO zushi;
CREATE EXTENSION IF NOT EXISTS vector;


DATABASE zushi OWNER zushi